{
    "input": {
        "pip_version": "24.2",
        "python_version": "3.8",
        "datetime": "2024-10-07T14:00:00",
        "platform_system": "Linux",
        "requirements": [
            "fsspec"
        ]
    },
    "result": {
        "success": false,
        "failure_reason": "WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPConnection object at 0x7f4819ee1e20>: Failed to establish a new connection: [Errno 111] Connection refused')': /fsspec/\nWARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPConnection object at 0x7f481a389190>: Failed to establish a new connection: [Errno 111] Connection refused')': /fsspec/\nWARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPConnection object at 0x7f481a389400>: Failed to establish a new connection: [Errno 111] Connection refused')': /fsspec/\n",
        "install_info": [
            {
                "file_name": "fsspec-2024.9.0-py3-none-any.whl",
                "hash": "sha256=a0947d552d8a6efa72cc2c730b12c41d043509156966cca4fb157b0f2a0c574b"
            }
        ]
    },
    "resolution": [
        {
            "requirement": "fsspec",
            "packages": [
                "fsspec-2024.9.0-py3-none-any.whl"
            ]
        }
    ]
}